//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int tranId { get; set; }
        public Nullable<int> offerID { get; set; }
        public Nullable<int> buyerID { get; set; }
        public System.DateTime tranDate { get; set; }
        public decimal salePrice { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual User User { get; set; }
    }
}
