//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int logInID { get; set; }
        public Nullable<int> userID { get; set; }
        public System.DateTime logInDateTime { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
    
        public virtual User User { get; set; }
    }
}
